/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmRegistrarEditarPaciente.java
 *
 * Created on 31/05/2012, 20:21:59
 */
package Vistas.ABMPacientes;

import Hibernate.IPersistencia;
import Modelo.Gestores.GestorPaciente;
import Modelo.Paciente;
import Vistas.ABMDomicilio.FrmDomicilio;
import Vistas.General.GestorABM;
import Vistas.General.IVistaABM;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXDatePicker;

                
    
    /**
 *
 * @author Nico
 */
public class FrmRegistrarEditarPaciente extends javax.swing.JInternalFrame implements IVistaABM{
    private GestorABM gestorAbm;
    /** Creates new form FrmRegistrarEditarPaciente */
    public FrmRegistrarEditarPaciente() {
        initComponents();
        gestorAbm=new GestorABMPaciente(this,null,new GestorPaciente(),new Paciente(),this.getFrmDomicilio1() );
        gestorAbm.inicializar();
    }
    
    public FrmRegistrarEditarPaciente(GestorAdminPaciente gestorAdmin,IPersistencia persistencia,Object objeto) {
        initComponents();
        gestorAbm=new GestorABMPaciente(this, gestorAdmin, persistencia, objeto,this.getFrmDomicilio1());
        gestorAbm.inicializar();
   }        

    @Override
    public GestorABM getGestor() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void setGestor(GestorABM gestor) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
   
/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtApellidoPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox();
        txtNumeroDocumento = new javax.swing.JTextField();
        cmbSexo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dtpFechaNacimiento = new org.jdesktop.swingx.JXDatePicker();
        txtEmail = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        frmDomicilio1 = new Vistas.ABMDomicilio.FrmDomicilio();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("Paciente");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Apellido");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 29, 50, 20);
        jPanel1.add(txtApellidoPaciente);
        txtApellidoPaciente.setBounds(80, 30, 152, 20);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 60, 50, 20);
        jPanel1.add(txtNombrePaciente);
        txtNombrePaciente.setBounds(80, 60, 152, 20);

        jLabel3.setText("Documento");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 60, 20);

        cmbTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTipoDocumento);
        cmbTipoDocumento.setBounds(80, 90, 50, 20);

        txtNumeroDocumento.setForeground(new java.awt.Color(204, 204, 204));
        txtNumeroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroDocumento);
        txtNumeroDocumento.setBounds(140, 90, 90, 20);

        jPanel1.add(cmbSexo);
        cmbSexo.setBounds(80, 120, 110, 20);

        jLabel4.setText("Sexo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 120, 60, 20);

        jLabel5.setText("Fecha Nac.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 70, 20);
        jPanel1.add(dtpFechaNacimiento);
        dtpFechaNacimiento.setBounds(80, 150, 110, 22);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(80, 180, 160, 20);

        jPanel5.setPreferredSize(new java.awt.Dimension(294, 132));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(frmDomicilio1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Domicilio", jPanel5);
        jTabbedPane2.addTab("Teléfonos", jPanel6);

        jPanel1.add(jTabbedPane2);
        jTabbedPane2.setBounds(270, 20, 330, 180);

        jLabel6.setText("E-mail");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 180, 60, 20);

        jTabbedPane1.addTab("Datos Personal", jPanel1);

        jPanel2.setLayout(null);

        jLabel7.setText("Nombre");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 10, 50, 20);

        jComboBox2.setMaximumRowCount(50);
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(60, 10, 120, 20);

        jLabel8.setText("Plan");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 40, 50, 20);

        jComboBox3.setMaximumRowCount(50);
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(60, 40, 120, 20);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(200, 10, 71, 23);

        jButton2.setText("Eliminar");
        jPanel2.add(jButton2);
        jButton2.setBounds(200, 40, 70, 23);

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jXTable1.setColumnFactory(null);
        jScrollPane1.setViewportView(jXTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(290, 10, 302, 200);

        jTabbedPane1.addTab("Obra Social", jPanel2);

        jPanel3.setLayout(null);
        jTabbedPane1.addTab("Familiares", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 10, 620, 250);

        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(460, 280, 80, 23);

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(550, 280, 80, 23);

        setBounds(0, 0, 660, 347);
    }// </editor-fold>//GEN-END:initComponents

private void txtNumeroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDocumentoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNumeroDocumentoActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void cmbTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDocumentoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmbTipoDocumentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JComboBox cmbTipoDocumento;
    private org.jdesktop.swingx.JXDatePicker dtpFechaNacimiento;
    private Vistas.ABMDomicilio.FrmDomicilio frmDomicilio1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JTextField txtApellidoPaciente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtNumeroDocumento;
    // End of variables declaration//GEN-END:variables

    public JTextField getApellidoPaciente() {
        return txtApellidoPaciente;
    }

    public void setApellidoPaciente(JTextField txtApellidoPaciente) {
        this.txtApellidoPaciente = txtApellidoPaciente;
    }

    public JTextField getEmail() {
        return txtEmail;
    }

    public void setEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextField getNombrePaciente() {
        return txtNombrePaciente;
    }

    public void setNombrePaciente(JTextField txtNombrePaciente) {
        this.txtNombrePaciente = txtNombrePaciente;
    }

    public JTextField getNumeroDocumento() {
        return txtNumeroDocumento;
    }

    public void setNumeroDocumento(JTextField txtNumeroDocumento) {
        this.txtNumeroDocumento = txtNumeroDocumento;
    }

    private FrmDomicilio getFrmDomicilio1() {
        return frmDomicilio1;
    }

    public void setFrmDomicilio1(FrmDomicilio frmDomicilio1) {
        this.frmDomicilio1 = frmDomicilio1;
    }

    public JComboBox getCmbSexo() {
        return cmbSexo;
    }

    public void setCmbSexo(JComboBox cmbSexo) {
        this.cmbSexo = cmbSexo;
    }

    public JComboBox getCmbTipoDocumento() {
        return cmbTipoDocumento;
    }

    public void setCmbTipoDocumento(JComboBox cmbTipoDocumento) {
        this.cmbTipoDocumento = cmbTipoDocumento;
    }

    public JXDatePicker getDtpFechaNacimiento() {
        return dtpFechaNacimiento;
    }

    public void setDtpFechaNacimiento(JXDatePicker dtpFechaNacimiento) {
        this.dtpFechaNacimiento = dtpFechaNacimiento;
    }

    
}
