/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAdminGeografia.java
 *
 * Created on 28/06/2012, 20:05:33
 */
package Vistas.ABMGeografia;

/**
 *
 * @author Nico
 */
public class FrmAdminGeografia extends javax.swing.JInternalFrame {

    /** Creates new form FrmAdminGeografia */
    public FrmAdminGeografia() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox();
        btnNuevaProvincia = new javax.swing.JButton();
        btnEditarProvincia = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLocalidad = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        btnNuevaLocalidad = new javax.swing.JButton();
        btnEditarLocalidad = new javax.swing.JButton();
        btnEliminarLocalidad = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel2.setText("Provincia");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 50, 20);

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbProvincia);
        cmbProvincia.setBounds(60, 20, 180, 20);

        btnNuevaProvincia.setText("Nuevo");
        btnNuevaProvincia.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(btnNuevaProvincia);
        btnNuevaProvincia.setBounds(250, 20, 70, 25);

        btnEditarProvincia.setText("Editar");
        btnEditarProvincia.setPreferredSize(new java.awt.Dimension(50, 20));
        getContentPane().add(btnEditarProvincia);
        btnEditarProvincia.setBounds(330, 20, 70, 25);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Localidad"));
        jPanel1.setLayout(null);

        lstLocalidad.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstLocalidad);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 210, 250);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        btnNuevaLocalidad.setText("Nuevo");
        btnNuevaLocalidad.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel2.add(btnNuevaLocalidad);
        btnNuevaLocalidad.setBounds(15, 10, 70, 25);

        btnEditarLocalidad.setText("Editar");
        btnEditarLocalidad.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel2.add(btnEditarLocalidad);
        btnEditarLocalidad.setBounds(15, 40, 70, 25);

        btnEliminarLocalidad.setText("Eliminar");
        btnEliminarLocalidad.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel2.add(btnEliminarLocalidad);
        btnEliminarLocalidad.setBounds(15, 70, 70, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(250, 30, 100, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 390, 300);

        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(320, 370, 80, 25);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-435)/2, (screenSize.height-442)/2, 435, 442);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarLocalidad;
    private javax.swing.JButton btnEditarProvincia;
    private javax.swing.JButton btnEliminarLocalidad;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevaLocalidad;
    private javax.swing.JButton btnNuevaProvincia;
    private javax.swing.JComboBox cmbProvincia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstLocalidad;
    // End of variables declaration//GEN-END:variables
}
