/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.ABMUsuario;

import Hibernate.IPersistencia;
import Modelo.Gestores.GestorUsuario;
import Modelo.Usuario;
import Vistas.General.GestorABM;
import Vistas.General.IVistaABM;
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Nico
 */
public class FrmRegistrarEditarUsuario extends javax.swing.JInternalFrame implements IVistaABM{
     private GestorABM gestorAbm;

    /**
     * Creates new form FrmRegistrarUsuario
     */
    public FrmRegistrarEditarUsuario() {
        initComponents();
        gestorAbm=new GestorABMUsuario(this,null,new GestorUsuario(),new Usuario (),null );
        gestorAbm.inicializar();
    }
    
    public FrmRegistrarEditarUsuario(GestorAdminUsuario gestorAdmin,IPersistencia persistencia,Object objeto) {
        initComponents();
        gestorAbm=new GestorABMUsuario(this, gestorAdmin, persistencia, objeto,null);
        gestorAbm.inicializar();
   }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlDatosUsuario = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTipoUsuario = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTipoUsuarioAplicado = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnAgregarTodo = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnQuitarTodo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pnlPermisosEspeciales = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Usuario");
        setMinimumSize(new java.awt.Dimension(70, 34));
        setNormalBounds(new java.awt.Rectangle(0, 0, 70, 0));
        setPreferredSize(new java.awt.Dimension(54, 34));
        getContentPane().setLayout(null);

        jTabbedPane1.setToolTipText("Datos");
        jTabbedPane1.setFocusable(false);

        pnlDatosUsuario.setFocusable(false);
        pnlDatosUsuario.setLayout(null);

        txtNombre.setText(" ");
        txtNombre.setFocusTraversalPolicyProvider(true);
        pnlDatosUsuario.add(txtNombre);
        txtNombre.setBounds(70, 20, 170, 20);

        txtApellido.setText(" ");
        txtApellido.setFocusTraversalPolicyProvider(true);
        pnlDatosUsuario.add(txtApellido);
        txtApellido.setBounds(70, 50, 170, 20);

        txtUsuario.setText(" ");
        txtUsuario.setFocusTraversalPolicyProvider(true);
        pnlDatosUsuario.add(txtUsuario);
        txtUsuario.setBounds(70, 80, 170, 20);

        txtMail.setText(" ");
        txtMail.setFocusTraversalPolicyProvider(true);
        pnlDatosUsuario.add(txtMail);
        txtMail.setBounds(70, 110, 170, 20);

        txtTelefono.setFocusTraversalPolicyProvider(true);
        pnlDatosUsuario.add(txtTelefono);
        txtTelefono.setBounds(70, 140, 170, 20);

        txtDomicilio.setFocusTraversalPolicyProvider(true);
        pnlDatosUsuario.add(txtDomicilio);
        txtDomicilio.setBounds(70, 170, 170, 20);

        jLabel1.setText("Nombre");
        jLabel1.setFocusable(false);
        pnlDatosUsuario.add(jLabel1);
        jLabel1.setBounds(10, 20, 55, 20);

        jLabel2.setText("Apellido");
        jLabel2.setFocusable(false);
        pnlDatosUsuario.add(jLabel2);
        jLabel2.setBounds(10, 50, 55, 20);

        jLabel3.setText("Usuario");
        jLabel3.setFocusable(false);
        pnlDatosUsuario.add(jLabel3);
        jLabel3.setBounds(10, 80, 55, 20);

        jLabel4.setText("e-Mail");
        jLabel4.setFocusable(false);
        pnlDatosUsuario.add(jLabel4);
        jLabel4.setBounds(10, 110, 55, 20);

        jLabel5.setText("Teléfono");
        jLabel5.setFocusable(false);
        pnlDatosUsuario.add(jLabel5);
        jLabel5.setBounds(10, 140, 50, 20);

        lstTipoUsuario.setFocusable(false);
        jScrollPane1.setViewportView(lstTipoUsuario);

        pnlDatosUsuario.add(jScrollPane1);
        jScrollPane1.setBounds(290, 30, 120, 180);

        lstTipoUsuarioAplicado.setFocusable(false);
        jScrollPane2.setViewportView(lstTipoUsuarioAplicado);

        pnlDatosUsuario.add(jScrollPane2);
        jScrollPane2.setBounds(480, 30, 120, 180);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlDatosUsuario.add(jSeparator1);
        jSeparator1.setBounds(270, 10, 10, 210);

        jLabel6.setText("Permisos Disponibles");
        jLabel6.setFocusable(false);
        pnlDatosUsuario.add(jLabel6);
        jLabel6.setBounds(290, 10, 120, 20);

        jLabel7.setText("Permisos Aplicados");
        jLabel7.setFocusable(false);
        pnlDatosUsuario.add(jLabel7);
        jLabel7.setBounds(480, 10, 120, 20);

        btnAgregar.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnAgregar.setText(">");
        btnAgregar.setFocusable(false);
        pnlDatosUsuario.add(btnAgregar);
        btnAgregar.setBounds(420, 40, 50, 25);

        btnAgregarTodo.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnAgregarTodo.setText(">>");
        btnAgregarTodo.setFocusable(false);
        pnlDatosUsuario.add(btnAgregarTodo);
        btnAgregarTodo.setBounds(420, 70, 50, 25);

        btnQuitar.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnQuitar.setText("<");
        btnQuitar.setFocusable(false);
        pnlDatosUsuario.add(btnQuitar);
        btnQuitar.setBounds(420, 100, 50, 25);

        btnQuitarTodo.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        btnQuitarTodo.setText("<<");
        btnQuitarTodo.setFocusable(false);
        pnlDatosUsuario.add(btnQuitarTodo);
        btnQuitarTodo.setBounds(420, 130, 50, 25);

        jLabel8.setText("Domicilio");
        jLabel8.setFocusable(false);
        pnlDatosUsuario.add(jLabel8);
        jLabel8.setBounds(10, 170, 60, 20);

        jTabbedPane1.addTab("Datos Personales", pnlDatosUsuario);

        javax.swing.GroupLayout pnlPermisosEspecialesLayout = new javax.swing.GroupLayout(pnlPermisosEspeciales);
        pnlPermisosEspeciales.setLayout(pnlPermisosEspecialesLayout);
        pnlPermisosEspecialesLayout.setHorizontalGroup(
            pnlPermisosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        pnlPermisosEspecialesLayout.setVerticalGroup(
            pnlPermisosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Permisos Especiales", pnlPermisosEspeciales);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 10, 620, 260);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Datos");

        jButton1.setText("Guardar");
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 280, 80, 23);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 280, 80, 23);

        setBounds(0, 0, 660, 347);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarTodo;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnQuitarTodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList lstTipoUsuario;
    private javax.swing.JList lstTipoUsuarioAplicado;
    private javax.swing.JPanel pnlDatosUsuario;
    private javax.swing.JPanel pnlPermisosEspeciales;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public GestorABM getGestor() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setGestor(GestorABM gestor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JTextField getApellido() {
        return txtApellido;
    }

    public void setApellido(JTextField txtApellido) {
        this.txtApellido = txtApellido;
    }

    public JTextField getEMail() {
        return txtMail;
    }

    public void setEMail(JTextField txtMail) {
        this.txtMail = txtMail;
    }

    public JTextField getNombre() {
        return txtNombre;
    }

    public void setNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getNombreUsuario() {
        return txtUsuario;
    }

    public void setNombreUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

    public JTextField getTelefono() {
        return txtTelefono;
    }

    public void setTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }
    
    
}
