/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Gestores.GestorUsuario;
import Modelo.Usuario;
import Vistas.Permisos.EstadoLogin;
import Vistas.Permisos.GestorSeguridad;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nico
 */
public class FrmInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicioSesion
     */
    public FrmInicioSesion() {
        initComponents();
        this.setSize(605,335);
        PnlLogin fondo = new PnlLogin(); 
        this.add(fondo,BorderLayout.CENTER);
        GestorSeguridad.getInstance();
        //this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        btnInicioSesion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion");
        getContentPane().setLayout(null);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(10, 260, 150, 20);

        btnInicioSesion.setText("Iniciar Sesion");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioSesion);
        btnInicioSesion.setBounds(360, 258, 100, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(480, 258, 100, 23);

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 240, 70, 14);

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 240, 80, 14);
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(180, 260, 150, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 230, 570, 2);

        setSize(new java.awt.Dimension(604, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        this.dispose();
        GestorSeguridad.getInstance().setUsuario(new Usuario());
        GestorUsuario gestorUsuario =new GestorUsuario();
        FrmPrincipal frmPrincipal = new FrmPrincipal();
        frmPrincipal.setVisible(true);
         
//        if(!this.txtUsuario.getText().isEmpty() && !String.copyValueOf(this.txtContraseña.getPassword()).isEmpty())
//        {
//            String msg = "";
//            //login usuario
//            EstadoLogin configUsuario = GestorSeguridad.getInstance().configUsuario(this.txtUsuario.getText(), String.copyValueOf(this.txtContraseña.getPassword()));
//            if(configUsuario == EstadoLogin.NO_EXISTE)
//            {
//                msg = "El usuario: "+this.txtUsuario.getText()+" no existe.";
//            }else if(configUsuario == EstadoLogin.ERROR_CLAVE)
//            {
//                msg = "Contraseña Incorrecta!";
//            }else{
//                int op = JOptionPane.showConfirmDialog(null, "Acceso Concedido.\n¿Desea cambiar la configuración actual?",
//                                                                    "Bienvenido: "+this.txtUsuario.getText(),JOptionPane.YES_NO_OPTION);
//                if(op == JOptionPane.OK_OPTION)
//                {
//                  /*  this.pnlLogin.setVisible(false);
//                    this.dcFecha.setEnabled(true);
//                    this.tftTipoCambio.setEditable(true);
//                    this.cmbAlmacen.setEnabled(true);
//                    this.cmbMoneda.setEnabled(true);
//                    lblLogo.setText("JVENTAS");
//                    this.setSize(pnlConfig.getWidth(), this.getHeight()+bntAceptar.getHeight());
//                    this.setLocationRelativeTo(null);
//                    this.bntAceptar.setVisible(true);
//                    this.bntCancelarConfig.setVisible(true);
//                */
//                }else{
//                    FrmPrincipal frmPrincipal = new FrmPrincipal();
//                    frmPrincipal.setVisible(true);
//                    this.dispose();
//                 }
//                return;
//            }            
//            JOptionPane.showMessageDialog(null, msg, "Error: no se pudo conectar.", JOptionPane.ERROR_MESSAGE);
//        }else{
//            JOptionPane.showMessageDialog(null, "Ingrese un nombre de usuario y su contraseña", "Error: Datos vacios.", JOptionPane.ERROR_MESSAGE);
//        }
//        
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicioSesion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
