/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAdminProfesional.java
 *
 * Created on 25/06/2012, 19:31:38
 */
package Vistas.ABMProfesional;

/**
 *
 * @author Nico
 */
public class FrmAdminProfesional extends javax.swing.JInternalFrame {

    /** Creates new form FrmAdminProfesional */
    public FrmAdminProfesional() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdmin = new Vistas.General.PnlAdmin();

        getContentPane().setLayout(null);
        getContentPane().add(panelAdmin);
        panelAdmin.setBounds(10, 100, 700, 260);

        setBounds(10, 10, 740, 460);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vistas.General.PnlAdmin panelAdmin;
    // End of variables declaration//GEN-END:variables
}
