/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmRegistrarLocalidad.java
 *
 * Created on 02/07/2012, 17:55:24
 */
package Vistas.ABMGeografia;

import javax.swing.JTextField;

/**
 *
 * @author Nico
 */
public class FrmRegistrarLocalidad extends javax.swing.JInternalFrame {

    /** Creates new form FrmRegistrarLocalidad */
    public FrmRegistrarLocalidad() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodPostal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProvincia = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 50, 20);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(60, 20, 210, 20);
        getContentPane().add(txtCodPostal);
        txtCodPostal.setBounds(320, 20, 50, 20);

        jLabel2.setText("CP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 20, 20, 20);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(200, 150, 80, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(290, 150, 80, 23);

        jScrollPane1.setViewportView(lstProvincia);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 360, 70);

        jLabel3.setText("Observaciones");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 90, 20);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
    }

    public JTextField getTxtCodPostal() {
        return txtCodPostal;
    }

    public void setTxtCodPostal(JTextField txtCodPostal) {
        this.txtCodPostal = txtCodPostal;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
}//GEN-LAST:event_btnGuardarActionPerformed

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstProvincia;
    private javax.swing.JTextField txtCodPostal;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
