/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.ABMCondicionIva;

/**
 *
 * @author Nico
 */
public class FrmAdministrarCondIVA extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmAdministrarCondIVA
     */
    public FrmAdministrarCondIVA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNuevoTipoIVA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipoIVA = new org.jdesktop.swingx.JXTable();
        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtPorcentajeIVA = new javax.swing.JTextField();

        setTitle("Tipo IVA");
        getContentPane().setLayout(null);

        txtNuevoTipoIVA.setForeground(new java.awt.Color(153, 153, 153));
        txtNuevoTipoIVA.setText("Nuevo Tipo IVA");
        getContentPane().add(txtNuevoTipoIVA);
        txtNuevoTipoIVA.setBounds(20, 20, 110, 20);

        tblTipoIVA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo IVA", "% IVA"
            }
        ));
        jScrollPane1.setViewportView(tblTipoIVA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 230, 170);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        btnAgregar.setText("Agregar");
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(10, 10, 80, 23);

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(10, 40, 80, 23);

        btnSalir.setText("Salir");
        jPanel1.add(btnSalir);
        btnSalir.setBounds(10, 70, 80, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(260, 20, 100, 110);

        txtPorcentajeIVA.setForeground(new java.awt.Color(153, 153, 153));
        txtPorcentajeIVA.setText("%");
        getContentPane().add(txtPorcentajeIVA);
        txtPorcentajeIVA.setBounds(140, 20, 110, 20);

        setBounds(0, 0, 397, 268);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable tblTipoIVA;
    private javax.swing.JTextField txtNuevoTipoIVA;
    private javax.swing.JTextField txtPorcentajeIVA;
    // End of variables declaration//GEN-END:variables
}
