/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAdministrarPaciente.java
 *
 * Created on 05/06/2012, 16:24:29
 */
package Vistas.ABMPacientes;

import Modelo.Gestores.GestorPaciente;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Nico
 */
public class FrmAdministrarPaciente extends javax.swing.JInternalFrame{
    private GestorAdminPaciente gestor;
    
    /** Creates new form FrmAdministrarPaciente */
    public FrmAdministrarPaciente() {
        initComponents();
   //     gestor=new GestorADMINPaciente(this,new GestorPaciente());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoNombre = new javax.swing.JTextField();
        cmbTipoDocumento = new javax.swing.JComboBox();
        txtNumeroDocumento = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlBotonera = new javax.swing.JPanel();
        btnNuevoPaciente = new javax.swing.JButton();
        btnEditarPaciente = new javax.swing.JButton();
        btnEliminarPaciente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new org.jdesktop.swingx.JXTable();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Administrar Pacientes");
        getContentPane().setLayout(null);

        pnlBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlBuscar.setPreferredSize(new java.awt.Dimension(460, 100));
        pnlBuscar.setLayout(null);

        jLabel1.setText("Apellido y Nombre");
        pnlBuscar.add(jLabel1);
        jLabel1.setBounds(20, 30, 100, 20);

        jLabel2.setText("Tipo Documento");
        pnlBuscar.add(jLabel2);
        jLabel2.setBounds(20, 60, 90, 20);
        pnlBuscar.add(txtApellidoNombre);
        txtApellidoNombre.setBounds(130, 30, 210, 20);

        pnlBuscar.add(cmbTipoDocumento);
        cmbTipoDocumento.setBounds(130, 60, 60, 20);
        pnlBuscar.add(txtNumeroDocumento);
        txtNumeroDocumento.setBounds(230, 60, 110, 20);

        btnBuscar.setText("Buscar");
        pnlBuscar.add(btnBuscar);
        btnBuscar.setBounds(360, 60, 80, 23);

        jLabel3.setText("N°");
        pnlBuscar.add(jLabel3);
        jLabel3.setBounds(210, 60, 20, 20);

        getContentPane().add(pnlBuscar);
        pnlBuscar.setBounds(10, 10, 460, 100);

        pnlBotonera.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBotonera.setLayout(null);

        btnNuevoPaciente.setText("Nuevo");
        btnNuevoPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPacienteActionPerformed(evt);
            }
        });
        pnlBotonera.add(btnNuevoPaciente);
        btnNuevoPaciente.setBounds(10, 10, 80, 23);

        btnEditarPaciente.setText("Editar");
        btnEditarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPacienteActionPerformed(evt);
            }
        });
        pnlBotonera.add(btnEditarPaciente);
        btnEditarPaciente.setBounds(10, 40, 80, 23);

        btnEliminarPaciente.setText("Eliminar");
        btnEliminarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlBotonera.add(btnEliminarPaciente);
        btnEliminarPaciente.setBounds(10, 70, 80, 23);

        getContentPane().add(pnlBotonera);
        pnlBotonera.setBounds(660, 10, 100, 100);

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPacientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 750, 270);

        btnSalir.setText("Salir");
        getContentPane().add(btnSalir);
        btnSalir.setBounds(680, 400, 80, 23);

        setBounds(10, 10, 790, 470);
    }// </editor-fold>//GEN-END:initComponents

private void btnNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPacienteActionPerformed
        // TODO add your handling code here:
        
}//GEN-LAST:event_btnNuevoPacienteActionPerformed

private void btnEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPacienteActionPerformed
        // TODO add your handling code here:
        
}//GEN-LAST:event_btnEditarPacienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditarPaciente;
    private javax.swing.JButton btnEliminarPaciente;
    private javax.swing.JButton btnNuevoPaciente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBotonera;
    private javax.swing.JPanel pnlBuscar;
    private org.jdesktop.swingx.JXTable tblPacientes;
    private javax.swing.JTextField txtApellidoNombre;
    private javax.swing.JTextField txtNumeroDocumento;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnEditarPaciente() {
        return btnEditarPaciente;
    }

    public void setBtnEditarPaciente(JButton btnEditarPaciente) {
        this.btnEditarPaciente = btnEditarPaciente;
    }

    public JButton getBtnEliminarPaciente() {
        return btnEliminarPaciente;
    }

    public void setBtnEliminarPaciente(JButton btnEliminarPaciente) {
        this.btnEliminarPaciente = btnEliminarPaciente;
    }

    public JButton getBtnNuevoPaciente() {
        return btnNuevoPaciente;
    }

    public void setBtnNuevoPaciente(JButton btnNuevoPaciente) {
        this.btnNuevoPaciente = btnNuevoPaciente;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JComboBox getCmbTipoDocumento() {
        return cmbTipoDocumento;
    }

    public void setCmbTipoDocumento(JComboBox cmbTipoDocumento) {
        this.cmbTipoDocumento = cmbTipoDocumento;
    }

    public GestorAdminPaciente getGestor() {
        return gestor;
    }

    public void setGestor(GestorAdminPaciente gestor) {
        this.gestor = gestor;
    }

    public JXTable getTblPacientes() {
        return tblPacientes;
    }

    public void setTblPacientes(JXTable tblPacientes) {
        this.tblPacientes = tblPacientes;
    }

    public JTextField getTxtApellidoNombre() {
        return txtApellidoNombre;
    }

    public void setTxtApellidoNombre(JTextField txtApellidoNombre) {
        this.txtApellidoNombre = txtApellidoNombre;
    }

    public JTextField getTxtNumeroDocumento() {
        return txtNumeroDocumento;
    }

    public void setTxtNumeroDocumento(JTextField txtNumeroDocumento) {
        this.txtNumeroDocumento = txtNumeroDocumento;
    }

}
