/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmAdminPaciente.java
 *
 * Created on 11-jun-2012, 19:49:23
 */
package Vistas.ABMPacientes;

import Modelo.Gestores.GestorPaciente;
import Modelo.Paciente;
import Vistas.General.GestorAdmin;
import Vistas.General.IVistaAdmin;
import Vistas.General.PnlAdmin;
import javax.swing.JComboBox;

/**
 *
 * @author Lisandro
 */
public class FrmAdminPaciente extends javax.swing.JInternalFrame implements IVistaAdmin {
    private GestorAdminPaciente gestor;
    
    /** Creates new form FrmAdminPaciente */
    public FrmAdminPaciente() {
       initComponents();
       gestor=new GestorAdminPaciente(this,new GestorPaciente(), panelAdmin,new Paciente());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdmin = new Vistas.General.PnlAdmin();
        cmbDocumento = new javax.swing.JComboBox();

        cmbDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmbDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDocumentoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmbDocumentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDocumento;
    private Vistas.General.PnlAdmin panelAdmin;
    // End of variables declaration//GEN-END:variables

   


    public JComboBox getDocumento() {
        return cmbDocumento;
    }

    public void setDocumento(JComboBox cmbDocumento) {
        this.cmbDocumento = cmbDocumento;
    }

    public PnlAdmin getPanelAdmin() {
        return panelAdmin;
    }

    public void setPanelAdmin(PnlAdmin panelAdmin) {
        this.panelAdmin = panelAdmin;
    }

    @Override
    public GestorAdmin getGestor() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void setGestor(GestorAdmin gestor) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

  
    
}

